### ISSUE TITLE
Support managing CC devices

### ISSUE THREAD

**Issue by Raymo111** [CharaChorder/nexus#11]
Support everything in GTM.

**Comment by rccarlson** [comment]
What's the target here? Full chord management? Just a subset of device interaction like only creating chords?

If this is a bigger target, this may be better as a Milestone

**Comment by Raymo111** [comment]
> What's the target here? Full chord management? Just a subset of device interaction like only creating chords?

The target is full management of all devices.

> When you say "support everything in GTM", that covers a lot of settings and parameters, but nothing with chords. Is that intentional?

Yes and no, I'm saying we should have another module implementing all GTM features, but we can also have another module for chords etc to implement all dot I/On manager features. Just not really planned atm.

> If this is a bigger target (e.g. full chord management), this may be better as a Milestone

Most of the issues I added just before making this repo public yesterday (including this one) were giant milestones we had planned internally, I just wanted to write them down publicly, hence the hastily created GitHub issues.
