### ISSUE TITLE
Hitting "Refresh" causes fields to appear and disappear

### ISSUE THREAD

**Issue by rccarlson** [CharaChorder/nexus#25]
https://github.com/CharaChorder/nexus/assets/43221493/a9b3804f-3e31-481a-a19f-fc76dc0e760d

Hitting refresh causes the "Last used" and "Avg speed" fields to unpredictably appear and disappear

**Comment by rccarlson** [comment]
appears to be resolved by f9a35eb6071d61c6f0aa24574349186a42f420ff

**Comment by Raymo111** [comment]
@rccarlson make sure you check the list of existing issues before creating new ones.
