### ISSUE TITLE
Move dependencies from test-requirements to requirements.txt

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/nexus#27]
```
Converting ui files to python...
sh: line 1: venv/bin/pyside6-uic: No such file or directory
```

I don't know the specifics but reference https://discord.com/channels/861730583092658206/1139602702045810818/1141715772624863304

**Comment by Raymo111** [comment]
Investigated and realized it wasn't an issue (https://discord.com/channels/861730583092658206/1139602702045810818/1141747188645498951)
