### ISSUE TITLE
Add new score column for sorting

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/nexus#36]
One of the things I implemented in https://typing-tech.github.io/CharaChorder-utilities/chordfinder.html was that I established a "score" for some of the words.  The algorithm was simple, `frequency*length of word`.  I wonder what y'alls thoughts are on including something similar in Nexus. 

The idea behind it is sort of like you should focus on creating chords for the words that will save you the most strokes, and if you character entry a word then the length is the amount of stroke so you can find the most impactful words to have chords for by looking at this vs just a pure frequency of the word.

**Comment by rccarlson** [comment]
Perhaps change the formula to `frequency * avg speed` to focus more on potential time savings?
