### ISSUE TITLE
Encrypt banlist entries

### ISSUE THREAD

**Issue by rccarlson** [CharaChorder/nexus#66]
Some phrases that need to be banned should not be stored in plaintext (eg passwords).
Add a ban list that stores the *hash* of the phrase and a description, not the phrase itself.
For example:

| Hash               | Description                            |
| ------------------ | -------------------------------------- |
| `4E8A3467C466E562` | GitHub password                        |
| `DFAFE074CBC1ED6C` | Credit card number                     |
| `3480DBE179616AFC` | Secret ingredient for the Krabby Patty |

When a word/phrase is being added to the database, its hash can be compared against this ban list to determine if it should be ignored.

This would prevent storage of passwords or other sensitive data in plaintext.

**Comment by Raymo111** [comment]
I was thinking about how to do this actually, because hashing doesn't really help since someone can easily use rainbow tables/brute force to reverse them. I think we'd have to encrypt it with a master password, cached in memory when you start Nexus.

**Comment by rccarlson** [comment]
You could salt the hashes with the machine name or just a random string

**Comment by Raymo111** [comment]
Neither of those salts would work, because the database needs to be portable and decryptable across boots.

**Comment by rccarlson** [comment]
The salt could be generated on first launch and stored in the SQLite database

**Comment by Raymo111** [comment]
That doesn't offer much security either, since anyone can just extract the salt. The danger of providing cryptographically insecure obfuscation is that users are lulled into a false sense of security, where they now think that their data is secure, and proceed to take less caution with their db file than if they know anyone can get their plaintext banlist. So until a cryptographically-secure way (i.e. encryption) is decided on, I'm going to keep the banlist plaintext. This issue is certainly valid though, just needs some more thought before implementation.

**Comment by xslendix** [comment]
Use the TPM to encrypt data?

**Comment by Raymo111** [comment]
You're not thinking cross-platform... This needs to be portable. I'm not sure why everyone is against my original encryption idea...

**Comment by rccarlson** [comment]
> I think we'd have to encrypt it with a master password, cached in memory when you start Nexus.

Somehow I missed your encryption idea. Hash it or something in memory to prevent malicious memory search and I'm good with that.

**Comment by Raymo111** [comment]
> What about a combination approach?
> 
> ```mermaid
> graph LR
>     UserPassword[User Password]
>     PublicSalt[Public Salt]
>     subgraph BanList
>         word1[word1 hash]
>         word2[word2 hash]
>     end
>     UserPassword --> |Unencrypts| BanList
>     TestWord[User input] --> |Hash with| PublicSalt --> |Compare against| word1 & word2
> ```

That looks great 👍

**Comment by rccarlson** [comment]
Slight revision to minimize exposure of the salt:
```mermaid
graph LR
    UserPassword[User Password]
    subgraph BanList
        salt[Salt]
        word1[word1 hash]
        word2[word2 hash]
    end
    UserPassword --> |Unencrypts| BanList
    TestWord[User input] --> |Hash with| salt --> |Compare against| word1 & word2
```

**Comment by Raymo111** [comment]
Salted hash + symmetric encryption here is unnecessarily complex. Instead it's easier to just do symmetric encryption with a shared key on every banlist entry and also encrypt each word typed with the same key, and compare the encrypted forms. This way a description column isn't needed either, and we can just decrypt all the entries when the user opens the banlist.
