### ISSUE TITLE
Implement chord logging

### ISSUE THREAD

**Issue by Raymo111** [CharaChorder/nexus#8]
Use the serial API to connect to attached device(s) to get user chord libraries, to validate chords (especially multi-word chords). Also implement pure timing-based detection for users that don't have serial port access permissions.

**Comment by rccarlson** [comment]
Notes for future implementation: Turn on Enable Serial Chord (parameter 5) to receive the chord hex code via serial every time a chord is entered. The message from CCOS will be the hex code and only the hex code
