### ISSUE TITLE
Freqlog DB file should be stored in XDG_DATA_HOME

### ISSUE THREAD

**Issue by GetPsyched** [CharaChorder/nexus#92]
Currently, the SQLite file for the Freqlog db is stored wherever you run the app. This breaks the app when running it from different directories where it thinks the DB doesn't exist anymore. This shouldn't happen.

On Linux, this DB must be stored in `XDG_DATA_HOME`, falling back onto `.local/share/nexus`. I'm unsure what the conventions are for Windows and MacOS.

**Comment by Raymo111** [comment]
This is already captured in #48.

**Comment by GetPsyched** [comment]
Ah, sorry; I didn't find that issue
